# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 19, 15, 57, 58, 804000, tzinfo=utc), verbose_name=b'date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='endtime',
            field=models.DateTimeField(default='2016-01-01', verbose_name=b'date deleted'),
            preserve_default=False,
        ),
    ]
