# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20160619_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='done',
            field=models.IntegerField(default=0),
        ),
    ]
