# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_item_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='endtime',
            field=models.DateTimeField(null=True, verbose_name=b'date deleted'),
        ),
    ]
