# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-25 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20160619_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('createdtime', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('starttime', models.DateTimeField(null=True, verbose_name=b'date deleted')),
                ('done', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
