# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20160625_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='style',
            field=models.CharField(default='blue', max_length=64),
            preserve_default=False,
        ),
    ]
