# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-09 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20160809_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ordernumber',
            new_name='order',
        ),
    ]
