# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20160809_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.AddField(
            model_name='item',
            name='ordernumber',
            field=models.IntegerField(default=0),
        ),
    ]
