# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_remove_item_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ordernumber',
            field=models.IntegerField(default=0),
        ),
    ]
