# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_item_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='checklist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.Checklist'),
            preserve_default=False,
        ),
    ]
