# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-02 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0018_auto_20160811_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createdtime', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('deletedtime', models.DateTimeField(null=True, verbose_name=b'date deleted')),
                ('active', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='listtype',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklist',
            name='user',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Checklist'),
        ),
    ]
