# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-02 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20170902_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='user',
            new_name='created_user',
        ),
        migrations.AlterField(
            model_name='item',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Checklist'),
        ),
    ]
