# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-05 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0024_auto_20170904_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 5, 2, 47, 53, 261895, tzinfo=utc), verbose_name=b'date created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Checklist'),
        ),
    ]
