# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-14 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_auto_20170908_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Checklist'),
        ),
    ]
