# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-14 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0027_auto_20170914_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='favorit',
            new_name='favorite',
        ),
        migrations.AlterField(
            model_name='item',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Checklist'),
        ),
    ]
